service: dynamodb-bulk-api

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: me-central-1
  environment:
    DYNAMODB_TABLE_NAME: study_sample

plugins:
  - serverless-iam-roles-per-function

functions:
  apiserver:
    handler: server.apiserver
    name: apiserver
    memorySize: 128 # mb
    timeout: 30 # seconds
    events:
      - http: ANY /
      - http: ANY /{proxy+}
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:BatchWriteItem"
          - "dynamodb:Scan"
        Resource: !GetAtt SampleTable.Arn

resources:
  Resources:
    SampleTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: study_sample
        AttributeDefinitions:
          - AttributeName: studyid
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: studyid
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 15
          WriteCapacityUnits: 15
